config/routes.rb
VibrogymDev::Application.routes.draw do
  devise_for :users, path: "",
    path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "pages#home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  resources :contents, only: [:index]
  resource :users, only: [:edit] do
    collection do
      put "update_password"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :full_name,
    :remember_me, :current_password
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    return contents_url
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def edit
    @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update_with_password params[:user]
      sign_in @user, bypass: true
      redirect_to contents_path
      flash[:notice] = "Updated Password Successfully"
    else
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link
    return controllers_path
  end
end

app/views/contents/index.html.erb
Contents

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VibrogymDev</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render "shared/navbar" %>
  </head>
  <body>
    <div>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
About Us

app/views/pages/contact.html.erb
Contact

app/views/pages/home.html.erb
Home

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".intro" %><%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% elsif notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"> <%= t ".title" %> </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% unless current_user %>
          <li class="<%= "active" if action_name == "home" %>">
            <%= link_to t(".home"), root_path %>
          </li>
          <li class="<%= "active" if action_name == "about" %>">
            <%= link_to t(".about"), about_path %>
          </li>
          <li class="<%= "active" if action_name == "contact" %>">
            <%= link_to t(".contact"), contact_path %>
          </li>
        <% else %>
          <li class="<%= "active" if controller_name == "contents" and
          action_name == "index" %>">
            <%= link_to "Contents", contents_path %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= "active" if controller_name == "sessions" and
          action_name == "new" %>">
          <% unless current_user %>
            <%= link_to new_user_session_path do %>
              <%= t ".log_in" %>
            <% end %>
          <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.full_name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to edit_users_path do %>
                  Change Password
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: "delete" do %>
                  <%= t ".log_out" %>
                <% end %>
              </li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="col-md-8">
  <%= form_for(@user, :url => { :action => "update_password" },
    html: { class: "form-horizontal"}) do |f| %>
    <fieldset>
      <legend><%= t(".legend") %></legend>
      <%= render "shared/error", object: f.object %>
      <div class="form-group">
        <%= f.label :password, "Password", class: "col-lg-4 control-label" %>
        <div class="col-lg-8">
          <%= f.password_field :password, autocomplete: :off,
           class: "form-control", placeholder: t(".password") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation , class: "col-lg-4 control-label" %>
        <div class="col-lg-8">
          <%= f.password_field :password_confirmation, autocomplete: :off,
           class: "form-control", placeholder: t(".password_confirmation") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :current_password, class: "col-lg-4 control-label" %>
        <div class="col-lg-8">
          <%= f.password_field :current_password, autocomplete: :off,
           class: "form-control", placeholder: t(".current_password") %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-8 col-lg-offset-4">
          <%= f.submit t(".update"), class: "btn btn-primary" %>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>